# Generated by Django 3.0.2 on 2020-03-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_cost_price',
            field=models.IntegerField(default=0),
        ),
    ]
