# Generated by Django 3.0.2 on 2020-01-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0002_auto_20200107_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_field',
        ),
    ]
