# Generated by Django 3.0.2 on 2020-01-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0005_auto_20200107_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiity_kg',
            new_name='quantity_kg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantiity_units',
            new_name='quantity_units',
        ),
    ]
