# Generated by Django 3.0.2 on 2020-03-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0006_auto_20200305_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
