# Generated by Django 3.0.2 on 2020-03-05 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0007_auto_20200305_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='date_purchased',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
