# Generated by Django 3.0.2 on 2020-01-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0008_auto_20200110_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
