# Generated by Django 3.0.2 on 2020-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0008_purchaseitem_date_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='date_purchased',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='month',
            field=models.CharField(default=3, max_length=100),
        ),
    ]
