# Generated by Django 3.0.2 on 2020-01-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0009_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(default='default.jpg', upload_to='upload_to="media/"'),
        ),
    ]
