# Generated by Django 3.0.2 on 2020-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0010_auto_20200305_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='month',
            field=models.IntegerField(default=3),
        ),
    ]
