# Generated by Django 3.0.2 on 2020-01-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0010_auto_20200110_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(default='default.jpg', upload_to='product_images/'),
        ),
    ]
