# Generated by Django 3.0.2 on 2020-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0011_auto_20200110_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_field',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
