# Generated by Django 3.0.2 on 2020-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0011_purchase_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='month',
        ),
    ]
