# Generated by Django 3.0.2 on 2020-01-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pointofsale', '0014_auto_20200111_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
