# Generated by Django 3.0.2 on 2020-01-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0015_auto_20200111_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='products',
            new_name='product',
        ),
    ]
