# Generated by Django 3.0.2 on 2020-01-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0017_purchaseitem_amount_entered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_kg',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_units',
        ),
    ]
