# Generated by Django 3.0.2 on 2020-01-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0019_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
    ]
