# Generated by Django 3.0.2 on 2020-02-20 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0020_remove_purchase_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
