# Generated by Django 3.0.2 on 2020-02-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0021_purchaseitem_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
