# Generated by Django 3.0.2 on 2020-02-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0022_auto_20200221_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='ordered_date',
        ),
    ]
