# Generated by Django 3.0.2 on 2020-02-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0023_remove_purchaseitem_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='item',
        ),
    ]
