# Generated by Django 3.0.2 on 2020-02-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0024_auto_20200226_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='product',
        ),
    ]
