# Generated by Django 3.0.2 on 2020-02-26 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0025_auto_20200226_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
