# Generated by Django 3.0.2 on 2020-02-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0026_purchaseitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='date_added',
        ),
    ]
