# Generated by Django 3.0.2 on 2020-02-29 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0027_remove_purchaseitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
